version: "3.9"
services:
    nginx:
        build: ./nginx/
        container_name: code-laravel-nginx
        working_dir: /home/src
        ports:
            - 8086:80
        volumes:
            - ./src:/home/src
    php:
        build: ./php/
        container_name: code-laravel-php
        working_dir: /home/src
        volumes: 
            - ./src:/home/src
            - ./src/storage/logs/php-fpm:/var/log/php-fpm
        env_file:
            - ./src/.env
    db:
        container_name: code-laravel-db
        image: mariadb:10.6.5
        env_file:
            - ./mysql/.env
        volumes:
            - ./mysql/data:/var/lib/mysql
        ports:
            - 3336:3306